version: 2.1

setup: true

orbs:
  codecov: codecov/codecov@1.2.3
  win: circleci/windows@2.4.0

jobs:
  build:
    docker:
      - image: circleci/node:14
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: CI=false yarn build
  test:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-ubuntu-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-ubuntu-{{ checksum "package.json" }}
      - run: yarn test
      - codecov/upload:
          file: "./coverage/lcov.info"
  test-windows:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-macos-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-macos-{{ checksum "package.json" }}
      - run: yarn test
      - codecov/upload:
          file: "./coverage/lcov.info"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - test-windows
